/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ScQueryField {
        /**
          * Fields can be passed as a JSON string or a parsed array of field definitions.
          * @default []
         */
        "fields": string | FieldDefinition[];
        /**
          * Optional class for the input field.
         */
        "inputClass": string;
    }
    interface ScSpreadsheetUploader {
        /**
          * @default '{}'
         */
        "apiHeaders": string;
        /**
          * @default 'POST'
         */
        "apiMethod": string;
        /**
          * @default ''
         */
        "apiUrl": string;
        /**
          * @default 'spreadsheet-data'
         */
        "storageKey": string;
    }
    interface ScTaxonomy {
        "name": string;
        "url": string;
        "value": string;
    }
    interface ScTextarea {
        "suggestionUrl": string;
        "textareaClass": string;
    }
}
export interface ScQueryFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScQueryFieldElement;
}
export interface ScTaxonomyCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScTaxonomyElement;
}
declare global {
    interface HTMLScQueryFieldElementEventMap {
        "queryChange": string;
        "querySubmit": string;
    }
    interface HTMLScQueryFieldElement extends Components.ScQueryField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScQueryFieldElementEventMap>(type: K, listener: (this: HTMLScQueryFieldElement, ev: ScQueryFieldCustomEvent<HTMLScQueryFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScQueryFieldElementEventMap>(type: K, listener: (this: HTMLScQueryFieldElement, ev: ScQueryFieldCustomEvent<HTMLScQueryFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScQueryFieldElement: {
        prototype: HTMLScQueryFieldElement;
        new (): HTMLScQueryFieldElement;
    };
    interface HTMLScSpreadsheetUploaderElement extends Components.ScSpreadsheetUploader, HTMLStencilElement {
    }
    var HTMLScSpreadsheetUploaderElement: {
        prototype: HTMLScSpreadsheetUploaderElement;
        new (): HTMLScSpreadsheetUploaderElement;
    };
    interface HTMLScTaxonomyElementEventMap {
        "valueChange": string;
    }
    interface HTMLScTaxonomyElement extends Components.ScTaxonomy, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScTaxonomyElementEventMap>(type: K, listener: (this: HTMLScTaxonomyElement, ev: ScTaxonomyCustomEvent<HTMLScTaxonomyElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScTaxonomyElementEventMap>(type: K, listener: (this: HTMLScTaxonomyElement, ev: ScTaxonomyCustomEvent<HTMLScTaxonomyElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScTaxonomyElement: {
        prototype: HTMLScTaxonomyElement;
        new (): HTMLScTaxonomyElement;
    };
    interface HTMLScTextareaElement extends Components.ScTextarea, HTMLStencilElement {
    }
    var HTMLScTextareaElement: {
        prototype: HTMLScTextareaElement;
        new (): HTMLScTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "sc-query-field": HTMLScQueryFieldElement;
        "sc-spreadsheet-uploader": HTMLScSpreadsheetUploaderElement;
        "sc-taxonomy": HTMLScTaxonomyElement;
        "sc-textarea": HTMLScTextareaElement;
    }
}
declare namespace LocalJSX {
    interface ScQueryField {
        /**
          * Fields can be passed as a JSON string or a parsed array of field definitions.
          * @default []
         */
        "fields"?: string | FieldDefinition[];
        /**
          * Optional class for the input field.
         */
        "inputClass"?: string;
        /**
          * Emitted whenever the query changes. The detail contains the current query string.
         */
        "onQueryChange"?: (event: ScQueryFieldCustomEvent<string>) => void;
        /**
          * Emitted when the user submits the query (e.g., pressing Enter on a complete filter). The detail contains the final query string.
         */
        "onQuerySubmit"?: (event: ScQueryFieldCustomEvent<string>) => void;
    }
    interface ScSpreadsheetUploader {
        /**
          * @default '{}'
         */
        "apiHeaders"?: string;
        /**
          * @default 'POST'
         */
        "apiMethod"?: string;
        /**
          * @default ''
         */
        "apiUrl"?: string;
        /**
          * @default 'spreadsheet-data'
         */
        "storageKey"?: string;
    }
    interface ScTaxonomy {
        "name"?: string;
        "onValueChange"?: (event: ScTaxonomyCustomEvent<string>) => void;
        "url"?: string;
        "value"?: string;
    }
    interface ScTextarea {
        "suggestionUrl"?: string;
        "textareaClass"?: string;
    }

    interface ScQueryFieldAttributes {
        "fields": string | FieldDefinition[];
        "inputClass": string;
    }
    interface ScSpreadsheetUploaderAttributes {
        "storageKey": string;
        "apiUrl": string;
        "apiMethod": string;
        "apiHeaders": string;
    }
    interface ScTaxonomyAttributes {
        "url": string;
        "name": string;
        "value": string;
    }
    interface ScTextareaAttributes {
        "suggestionUrl": string;
        "textareaClass": string;
    }

    interface IntrinsicElements {
        "sc-query-field": Omit<ScQueryField, keyof ScQueryFieldAttributes> & { [K in keyof ScQueryField & keyof ScQueryFieldAttributes]?: ScQueryField[K] } & { [K in keyof ScQueryField & keyof ScQueryFieldAttributes as `attr:${K}`]?: ScQueryFieldAttributes[K] } & { [K in keyof ScQueryField & keyof ScQueryFieldAttributes as `prop:${K}`]?: ScQueryField[K] };
        "sc-spreadsheet-uploader": Omit<ScSpreadsheetUploader, keyof ScSpreadsheetUploaderAttributes> & { [K in keyof ScSpreadsheetUploader & keyof ScSpreadsheetUploaderAttributes]?: ScSpreadsheetUploader[K] } & { [K in keyof ScSpreadsheetUploader & keyof ScSpreadsheetUploaderAttributes as `attr:${K}`]?: ScSpreadsheetUploaderAttributes[K] } & { [K in keyof ScSpreadsheetUploader & keyof ScSpreadsheetUploaderAttributes as `prop:${K}`]?: ScSpreadsheetUploader[K] };
        "sc-taxonomy": Omit<ScTaxonomy, keyof ScTaxonomyAttributes> & { [K in keyof ScTaxonomy & keyof ScTaxonomyAttributes]?: ScTaxonomy[K] } & { [K in keyof ScTaxonomy & keyof ScTaxonomyAttributes as `attr:${K}`]?: ScTaxonomyAttributes[K] } & { [K in keyof ScTaxonomy & keyof ScTaxonomyAttributes as `prop:${K}`]?: ScTaxonomy[K] };
        "sc-textarea": Omit<ScTextarea, keyof ScTextareaAttributes> & { [K in keyof ScTextarea & keyof ScTextareaAttributes]?: ScTextarea[K] } & { [K in keyof ScTextarea & keyof ScTextareaAttributes as `attr:${K}`]?: ScTextareaAttributes[K] } & { [K in keyof ScTextarea & keyof ScTextareaAttributes as `prop:${K}`]?: ScTextarea[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sc-query-field": LocalJSX.IntrinsicElements["sc-query-field"] & JSXBase.HTMLAttributes<HTMLScQueryFieldElement>;
            "sc-spreadsheet-uploader": LocalJSX.IntrinsicElements["sc-spreadsheet-uploader"] & JSXBase.HTMLAttributes<HTMLScSpreadsheetUploaderElement>;
            "sc-taxonomy": LocalJSX.IntrinsicElements["sc-taxonomy"] & JSXBase.HTMLAttributes<HTMLScTaxonomyElement>;
            "sc-textarea": LocalJSX.IntrinsicElements["sc-textarea"] & JSXBase.HTMLAttributes<HTMLScTextareaElement>;
        }
    }
}
